//! Per-session SSH credential management for the daemon-mediated SSH
//! proxy.
//!
//! [`SshKeypair`] is the on-disk shape of a container session's
//! ed25519 keypair. Generated by the daemon at session-create time and
//! persisted in the `sessions.ssh_keypair_json` column added by V007,
//! it is consumed by:
//!
//! - the container-runtime injection path, which writes the public
//!   half into the container at `/run/sandbox/authorized_keys` via a
//!   tmpfs bind-mount (see `backend::container`);
//! - the `GET /sessions/{id}/ssh-config` handler, which serves the
//!   private half plus a ready-to-include SSH client config block to
//!   the session's owner (see the cross-user CLI access spec for the
//!   exact config template).
//!
//! # Trust model (load-bearing)
//!
//! Per the cross-user CLI access spec security considerations: any
//! member of the `sandbox` OS group can reach the daemon socket and
//! therefore request the private key via the API. The plaintext-at-rest
//! storage in `sessions.db` (file mode 0600, enforced in
//! `SessionStore::new`) is the security boundary, not in-process
//! secrecy. Do not weaken the file-mode contract on the persistence
//! site without revisiting that premise. Encryption-at-rest and
//! short-lived SSH certificates were both considered and explicitly
//! deferred — they would shrink the blast radius of a leaked key on a
//! compromised host but do not remove the underlying trust assumption
//! (the daemon-mediated proxy is still required to *reach* the
//! session's sshd regardless of credential shape).
//!
//! # Wire / persistence shape
//!
//! Both halves are serialised as OpenSSH-format strings — the same
//! shape `~/.ssh/id_ed25519` / `~/.ssh/id_ed25519.pub` carry, so the
//! CLI can write them out byte-for-byte into the per-session entry
//! under `~/.ssh/sandbox/keys/<id>`. JSON envelope:
//!
//! ```json
//! { "public": "ssh-ed25519 AAAA... sandbox-<id>",
//!   "private": "-----BEGIN OPENSSH PRIVATE KEY-----\n...\n-----END OPENSSH PRIVATE KEY-----\n" }
//! ```

use serde::{Deserialize, Serialize};
use ssh_key::rand_core::OsRng;
use ssh_key::{Algorithm, LineEnding, PrivateKey};

use crate::error::SandboxError;

/// OpenSSH comment stamped onto every generated public key.
///
/// The comment is purely cosmetic — sshd does not consult it during
/// authentication, but it gives operators a clue when they encounter a
/// stray sandbox key in `~/.ssh/sandbox/keys/<id>`. The per-session
/// `<id>` suffix is added by [`SshKeypair::generate`].
const SSH_KEY_COMMENT_PREFIX: &str = "sandbox";

/// Placeholder rendered into the generated SSH config in place of the
/// per-operator `IdentityFile` path. The CLI replaces this token with
/// the absolute path of the on-disk key under
/// `~/.ssh/sandbox/keys/<id>` when it writes the managed config block.
///
/// Pinned as a named constant so M18-S5's CLI consumer can match the
/// exact token verbatim; renaming it without coordinating both ends
/// is a wire break (the CLI scans the daemon-emitted block for the
/// placeholder and silently no-ops if it disappears).
pub const SSH_CONFIG_IDENTITY_FILE_PLACEHOLDER: &str = "<CLI-rewrites-this>";

/// Render the SSH client config block for the session `id`.
///
/// Output is the multi-line template called out in the cross-user CLI
/// access spec § Daemon API → `GET /sessions/{id}/ssh-config`. The
/// shape is wire-format from this point on; every line is consumed by
/// some downstream — the operator's `ssh` client, M18-S5's CLI module,
/// the `Host sandbox-<id>` alias resolution path, etc. Rewording a
/// directive or reordering the block is a wire break.
///
/// `HostName 127.0.0.1` and `Port 22` are deliberately placeholder
/// values — the actual connection is opened by the `ProxyCommand`
/// shim, so `ssh` never opens a socket to them, but the directives
/// must syntactically be present. `IdentityFile` carries the
/// [`SSH_CONFIG_IDENTITY_FILE_PLACEHOLDER`] token the CLI rewrites
/// per-operator before exec'ing `ssh`.
///
/// `StrictHostKeyChecking no` / `UserKnownHostsFile /dev/null` are
/// load-bearing per the spec's security considerations: the in-session
/// sshd is reached only through the daemon-mediated tunnel, so there
/// is no MITM surface between the SSH client and the sshd, and a
/// known-hosts dance would otherwise force operators through a
/// fingerprint prompt on every fresh session.
pub fn render_ssh_config_block(session_id: &str) -> String {
    // Note: SSH config indentation is two spaces by convention; do not
    // change to tabs (the operator's `ssh` parses either, but the
    // M18-S5 CLI tests pin this exact whitespace).
    //
    // `id` is the inline-format binding for `session_id`; `ph` is the
    // local rename of `SSH_CONFIG_IDENTITY_FILE_PLACEHOLDER` so the
    // format-string args are inline (clippy::uninlined_format_args).
    let id = session_id;
    let ph = SSH_CONFIG_IDENTITY_FILE_PLACEHOLDER;
    format!(
        "Host sandbox-{id}\n  \
         HostName 127.0.0.1\n  \
         Port 22\n  \
         User sandbox\n  \
         ProxyCommand sandbox proxy {id}\n  \
         IdentityFile {ph}\n  \
         UserKnownHostsFile /dev/null\n  \
         StrictHostKeyChecking no\n  \
         ServerAliveInterval 30\n  \
         ControlMaster auto\n  \
         ControlPath ~/.ssh/sandbox/sockets/%C\n  \
         ControlPersist 60\n",
    )
}

/// Per-session SSH keypair persisted in the `sessions.ssh_keypair_json`
/// column (V007 migration).
///
/// Both fields are OpenSSH-format strings so the CLI can write them
/// directly into the operator's `~/.ssh/sandbox/keys/<id>` area
/// without re-encoding. The struct is `Clone` because the daemon
/// commonly hands a copy to both the injection path (container
/// backend) and the `ssh-config` response builder during the same
/// session-create call.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SshKeypair {
    /// OpenSSH-formatted public key — the exact bytes that go into
    /// `authorized_keys`. Includes the `ssh-ed25519` algorithm tag, the
    /// base64-encoded key material, and the sandbox comment.
    pub public: String,
    /// OpenSSH-formatted private key (the PEM-style block starting
    /// with `-----BEGIN OPENSSH PRIVATE KEY-----`). Suitable for
    /// dropping into `~/.ssh/sandbox/keys/<id>` with mode 0600.
    pub private: String,
}

impl SshKeypair {
    /// Generate a fresh ed25519 keypair using the system RNG.
    ///
    /// `session_id` is woven into the public-key OpenSSH comment so a
    /// key that escapes its session directory can still be traced back
    /// to the originating session via `ssh-keygen -l -f <file>`.
    ///
    /// Errors surface as [`SandboxError::Internal`] — keypair
    /// generation through `ssh-key` only fails if the RNG itself is
    /// broken, which is a host-environment failure the daemon should
    /// not paper over.
    pub fn generate(session_id: &str) -> Result<Self, SandboxError> {
        let mut rng = OsRng;
        let mut private_key = PrivateKey::random(&mut rng, Algorithm::Ed25519).map_err(|e| {
            SandboxError::Internal(format!("ed25519 keypair generation failed: {e}"))
        })?;
        private_key.set_comment(format!("{SSH_KEY_COMMENT_PREFIX}-{session_id}"));

        let private = private_key
            .to_openssh(LineEnding::LF)
            .map_err(|e| {
                SandboxError::Internal(format!("ed25519 private key OpenSSH encode failed: {e}"))
            })?
            .to_string();

        let public = private_key.public_key().to_openssh().map_err(|e| {
            SandboxError::Internal(format!("ed25519 public key OpenSSH encode failed: {e}"))
        })?;

        Ok(Self { public, private })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_produces_openssh_format_pubkey() {
        let kp = SshKeypair::generate("0123456789ab").expect("generate");
        assert!(
            kp.public.starts_with("ssh-ed25519 "),
            "public key must carry the ssh-ed25519 tag, got: {pub}",
            pub = kp.public,
        );
        assert!(
            kp.public.ends_with("sandbox-0123456789ab"),
            "public key must carry the sandbox-<id> comment, got: {pub}",
            pub = kp.public,
        );
    }

    #[test]
    fn generate_produces_openssh_format_privkey() {
        let kp = SshKeypair::generate("0123456789ab").expect("generate");
        assert!(
            kp.private.starts_with("-----BEGIN OPENSSH PRIVATE KEY-----"),
            "private key must be OpenSSH-format, got: {priv}",
            priv = kp.private,
        );
        assert!(
            kp.private
                .trim_end()
                .ends_with("-----END OPENSSH PRIVATE KEY-----"),
            "private key must terminate with the OpenSSH end marker, got: {priv}",
            priv = kp.private,
        );
    }

    #[test]
    fn generated_keypair_round_trips_through_ssh_key() {
        // Sanity-check that a freshly generated keypair re-parses
        // cleanly through `ssh-key`'s own decoders. This guards against
        // a subtle encoder-bug that produced bytes only our own
        // serialiser would accept; if the bytes round-trip through
        // ssh-key they will also round-trip through `sshd`, `ssh`, and
        // every other OpenSSH consumer.
        let kp = SshKeypair::generate("ffeeddccbbaa").expect("generate");
        let parsed_pub = ssh_key::PublicKey::from_openssh(&kp.public).expect("re-parse pubkey");
        assert!(matches!(parsed_pub.algorithm(), Algorithm::Ed25519));

        let parsed_priv = ssh_key::PrivateKey::from_openssh(&kp.private).expect("re-parse privkey");
        assert!(matches!(parsed_priv.algorithm(), Algorithm::Ed25519));

        // Re-derived pubkey must match the persisted one, byte-for-byte.
        let re_derived_pub = parsed_priv
            .public_key()
            .to_openssh()
            .expect("re-encode pubkey");
        assert_eq!(re_derived_pub, kp.public);
    }

    #[test]
    fn each_generate_call_produces_a_distinct_keypair() {
        // Sanity-check: two consecutive calls must not collide on the
        // RNG seed. Catches a regression where someone accidentally
        // swaps `OsRng` for a deterministic test RNG and ships it.
        let a = SshKeypair::generate("aaaaaaaaaaaa").expect("first");
        let b = SshKeypair::generate("aaaaaaaaaaaa").expect("second");
        assert_ne!(
            a.public, b.public,
            "two consecutive keypairs collided — RNG seeding is broken"
        );
        assert_ne!(a.private, b.private);
    }

    #[test]
    fn serde_round_trip_preserves_both_halves() {
        let kp = SshKeypair::generate("112233445566").expect("generate");
        let json = serde_json::to_string(&kp).expect("serialise");
        let back: SshKeypair = serde_json::from_str(&json).expect("deserialise");
        assert_eq!(back, kp);
    }

    #[test]
    fn render_ssh_config_block_matches_spec_template() {
        // Pin the exact byte sequence against the spec template. A
        // line-reorder / directive-rename here is a wire break with
        // M18-S5's CLI consumer.
        let block = render_ssh_config_block("0123456789ab");
        let expected = "\
Host sandbox-0123456789ab
  HostName 127.0.0.1
  Port 22
  User sandbox
  ProxyCommand sandbox proxy 0123456789ab
  IdentityFile <CLI-rewrites-this>
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  ServerAliveInterval 30
  ControlMaster auto
  ControlPath ~/.ssh/sandbox/sockets/%C
  ControlPersist 60
";
        assert_eq!(block, expected, "config block deviated from spec template");
    }

    #[test]
    fn render_ssh_config_block_threads_session_id_into_proxy_and_host() {
        // The session id must appear in both the `Host` alias and the
        // `ProxyCommand` argv — M18-S5's CLI alias resolution and the
        // daemon proxy WebSocket endpoint both depend on the exact
        // string. Tested independently from the byte-equal template
        // assertion so a partial regression on either site shows up
        // distinctly.
        let id = "ffeeddccbbaa";
        let block = render_ssh_config_block(id);
        assert!(
            block.contains(&format!("Host sandbox-{id}")),
            "missing Host alias line: {block}"
        );
        assert!(
            block.contains(&format!("ProxyCommand sandbox proxy {id}")),
            "missing ProxyCommand line: {block}"
        );
    }

    #[test]
    fn render_ssh_config_block_contains_identity_file_placeholder() {
        // The placeholder token is wire format — M18-S5's CLI scans
        // the block for it and overwrites in-place with the real
        // per-session key path. Renaming the token is a wire break.
        let block = render_ssh_config_block("0123456789ab");
        assert!(
            block.contains(SSH_CONFIG_IDENTITY_FILE_PLACEHOLDER),
            "config block must carry the IdentityFile placeholder for the CLI to rewrite; \
             got: {block}"
        );
    }

    #[test]
    fn serde_wire_shape_matches_documented_envelope() {
        // Pin the on-disk JSON shape: `{"public": "...", "private":
        // "..."}`. The CLI reads this envelope back when serving the
        // ssh-config endpoint, so a rename of either key is a wire
        // break.
        let kp = SshKeypair {
            public: "ssh-ed25519 AAAA test".into(),
            private:
                "-----BEGIN OPENSSH PRIVATE KEY-----\ntest\n-----END OPENSSH PRIVATE KEY-----\n"
                    .into(),
        };
        let value: serde_json::Value = serde_json::to_value(&kp).expect("to_value");
        assert!(
            value.get("public").is_some(),
            "envelope must carry `public`"
        );
        assert!(
            value.get("private").is_some(),
            "envelope must carry `private`"
        );
    }
}
